<?php

class ConstConfig
{
	const USER_LOGIN_SUCCESS = 1001;
	const USER_LOGIN_ERROR_AUTH_FAIL = 1008;
	const USER_LOGIN_ERROR_NO_PARAM = 1009;

	const USER_REGISTER_SUCCESS = 2001;
	const USER_REGISTER_ERROR_DUPLICATED = 2007;
	const USER_REGISTER_ERROR_AUTH_FAIL = 2008;
	const USER_REGISTER_ERROR_NO_PARAM = 2009;
	
	const GET_ROLE_SUCCESS = 3001;
	const GET_ROLE_ERROR_NO_PARAM = 3002;

	const CHOOSE_ROLE_SUCCESS = 4001;
	const CHOOSE_ROLE_ERROR_NOT_EXIST = 4002;
	const CHOOSE_ROLE_ERROR_NOT_MATCH = 4003;
	const CHOOSE_ROLE_ERROR_NO_PARAM = 4004;

	const CREATE_ROLE_SUCCESS = 5001;
	const CREATE_ROLE_ERROR_DUPLICATED = 5002;
	const CREATE_ROLE_ERROR_NO_PARAM = 5003;

	const GET_PLANET_SUCCESS = 6001;
	const GET_PLANET_ERROR_NO_PARAM = 6002;

	const GET_BUILDING_SUCCESS = 7001;
	const GET_BUILDING_ERROR_NO_PARAM = 7002;
}